// Mocks generated by Mockito 5.4.1 from annotations
// in posay/test/features/intro/domain/usecases/intro_usecase_test.dart.
// Do not manually edit this file.

// @dart=2.19

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:mockito/mockito.dart' as _i1;
import 'package:posay/features/intro/domain/entities/intro.dart' as _i3;
import 'package:posay/features/intro/domain/repositories/intro_repository.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [IntroRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIntroRepository extends _i1.Mock implements _i2.IntroRepository {
  @override
  List<_i3.Intro> getIntroContents(dynamic appLocalizations) =>
      (super.noSuchMethod(
        Invocation.method(
          #getIntroContents,
          [appLocalizations],
        ),
        returnValue: <_i3.Intro>[],
        returnValueForMissingStub: <_i3.Intro>[],
      ) as List<_i3.Intro>);
}
